/** Seed Alfondo — catálogo plano (precios lista Excel 2026). */
import type { ProductSeed } from "@/lib/products";

export const ALFONDO_PRODUCTS_SEED: ProductSeed[] = [
  {
    key: "revision_semilla_inicia",
    name: "Revisión Semilla Inicia",
    priceListClp: 297500,
    paymentLink: "https://mpago.li/1y8z1pZ",
    active: true,
  },
  {
    key: "formulacion_semilla_inicia",
    name: "Formulación Semilla Inicia",
    priceListClp: 750000,
    paymentLink: "https://mpago.li/2tAXnks",
    active: true,
  },
  {
    key: "revision_semilla_expande",
    name: "Revisión Semilla Expande",
    priceListClp: 375000,
    paymentLink: "https://mpago.li/2Cu7Brt",
    active: true,
  },
  {
    key: "formulacion_semilla_expande",
    name: "Formulación Semilla Expande",
    priceListClp: 1125000,
    paymentLink: "https://mpago.li/2mFH3Kd",
    active: true,
  },
  {
    key: "revision_escalamiento",
    name: "Revisión Escalamiento",
    priceListClp: 445000,
    paymentLink: "https://mpago.li/321oPGx",
    active: true,
  },
  {
    key: "formulacion_escalamiento",
    name: "Formulación Escalamiento",
    priceListClp: 1500000,
    paymentLink: "https://mpago.li/1w4oVHR",
    active: true,
  },
  {
    key: "revision_sumate_a_innovar",
    name: "Revisión Súmate a Innovar",
    priceListClp: 297500,
    paymentLink: "https://mpago.li/1H71DYx",
    active: true,
  },
  {
    key: "formulacion_sumate_a_innovar",
    name: "Formulación Súmate a Innovar",
    priceListClp: 750000,
    paymentLink: "https://mpago.li/2kdUbYR",
    active: true,
  },
  {
    key: "revision_innova_region",
    name: "Revisión Innova Región",
    priceListClp: 600000,
    paymentLink: "https://mpago.li/2vcygfa",
    active: true,
  },
  {
    key: "formulacion_innova_region",
    name: "Formulación Innova Región",
    priceListClp: 1500000,
    paymentLink: "https://mpago.li/2tDDhQk",
    active: true,
  },
  {
    key: "revision_crea_y_valida",
    name: "Revisión Crea y Valida",
    priceListClp: 1190000,
    paymentLink: "https://mpago.li/2ZtWZR9",
    active: true,
  },
  {
    key: "formulacion_crea_y_valida",
    name: "Formulación Crea y Valida",
    priceListClp: 4500000,
    paymentLink: "https://mpago.li/1tVBn5a",
    active: true,
  },
  {
    key: "revision_consolida_y_expande",
    name: "Revisión Consolida y Expande",
    priceListClp: 1190000,
    paymentLink: "https://mpago.li/2Sp7udx",
    active: true,
  },
  {
    key: "formulacion_consolida_y_expande",
    name: "Formulación Consolida y Expande",
    priceListClp: 3750000,
    paymentLink: "https://mpago.li/2BLqvrb",
    active: true,
  },
  {
    key: "formulacion_capital_humano_para_la_innovacion",
    name: "Formulación Capital Humano para la Innovación",
    priceListClp: null,
    paymentLink: null,
    active: false,
  },
  {
    key: "formulacion_fia_fondos_de_interes_privado",
    name: "Formulación FIA : Fondos de Interés Privado",
    priceListClp: null,
    paymentLink: null,
    active: false,
  },
  {
    key: "consultoria_innovacion_i_d",
    name: "Consultoría Innovación / I+D",
    priceListClp: 500000,
    paymentLink: null,
    active: true,
  },
  {
    key: "revision_startup_chile_build",
    name: "Revisión Startup Chile Build",
    priceListClp: 297500,
    paymentLink: "https://mpago.li/2eekbTA",
    active: true,
  },
  {
    key: "formulacion_startup_chile_build",
    name: "Formulación Startup Chile Build",
    priceListClp: 750000,
    paymentLink: "https://mpago.li/2TMLGzj",
    active: true,
  },
  {
    key: "revision_startup_chile_ignite",
    name: "Revisión Startup Chile Ignite",
    priceListClp: 375000,
    paymentLink: "https://mpago.li/1uziDq2",
    active: true,
  },
  {
    key: "formulacion_startup_chile_ignite",
    name: "Formulación Startup Chile Ignite",
    priceListClp: 1125000,
    paymentLink: "https://mpago.li/2T9Qxu6",
    active: true,
  },
  {
    key: "revision_startup_chile_growth",
    name: "Revisión Startup Chile Growth",
    priceListClp: 445000,
    paymentLink: "https://mpago.li/167LuWc",
    active: true,
  },
  {
    key: "formulacion_startup_chile_growth",
    name: "Formulación Startup Chile Growth",
    priceListClp: 1500000,
    paymentLink: "https://mpago.li/1XKM8uN",
    active: true,
  },
  {
    key: "revision_desarrolla_inversion",
    name: "Revisión Desarrolla Inversión",
    priceListClp: 375000,
    paymentLink: "https://mpago.li/2dzmmFy",
    active: true,
  },
  {
    key: "formulacion_desarrolla_inversion",
    name: "Formulación Desarrolla Inversión",
    priceListClp: 750000,
    paymentLink: "https://mpago.li/1yoi5M1",
    active: true,
  },
  {
    key: "revision_semilla_emprende",
    name: "Revisión Semilla Emprende",
    priceListClp: 197000,
    paymentLink: "https://mpago.li/1VCcUBN",
    active: true,
  },
  {
    key: "formulacion_semilla_emprende",
    name: "Formulación Semilla Emprende",
    priceListClp: 327000,
    paymentLink: "https://mpago.li/19Fgcuq",
    active: true,
  },
  {
    key: "revision_capital_abeja",
    name: "Revisión Capital Abeja",
    priceListClp: 197000,
    paymentLink: "https://mpago.li/1WSCsmn",
    active: true,
  },
  {
    key: "formulacion_capital_abeja",
    name: "Formulación Capital Abeja",
    priceListClp: 327000,
    paymentLink: "https://mpago.li/2XzRnpP",
    active: true,
  },
  {
    key: "revision_capital_pioneras",
    name: "Revisión Capital Pioneras",
    priceListClp: 197000,
    paymentLink: "https://mpago.li/2qBceub",
    active: true,
  },
  {
    key: "formulacion_capital_pioneras",
    name: "Formulación Capital Pioneras",
    priceListClp: 327000,
    paymentLink: "https://mpago.li/2NwFGYT",
    active: true,
  },
  {
    key: "revision_crece",
    name: "Revisión CRECE",
    priceListClp: 197000,
    paymentLink: "https://mpago.li/22vwK3Y",
    active: true,
  },
  {
    key: "formulacion_crece",
    name: "Formulación CRECE",
    priceListClp: 327000,
    paymentLink: "https://mpago.li/1YekuVW",
    active: true,
  },
  {
    key: "revision_crece_sostenible",
    name: "Revisión CRECE Sostenible",
    priceListClp: 247000,
    paymentLink: "https://mpago.li/1aswWRX",
    active: true,
  },
  {
    key: "formulacion_crece_sostenible",
    name: "Formulación CRECE Sostenible",
    priceListClp: 450000,
    paymentLink: "https://mpago.li/2G5T4fv",
    active: true,
  },
];
